### ISSUE TITLE
lilla locurto podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#252] opened 2015-08-24 21:57 UTC
corey
please apologise to her and follow up

roger

Hi Roger,

I received an email from Corey Smart about the podcast and an attached pdf production cheat sheet. I wrote several times to see if there’s a deadline for submitting the podcast but never heard back. It’s still summer so I’m sure everyone is on vacation. Anyway, if you get this email, can you answer my question. We’re leaving for Europe in September and we don’t think we'll have time to do the podcast before we go.  Best, Lilla

On Jul 7, 2015, at 11:14 AM, roger malina rmalina@alum.mit.edu wrote:

lilla
excellent
will have a member of our team contact you with instructions
roger

On Mon, Jul 6, 2015 at 4:47 PM, Lilla LoCurto loc.out@verizon.net wrote:

Dear Mr. Malina,

My partner and I would be very interested in doing a podcast with two
colleagues of ours. We’re artists and our colleagues are computational
analysts with interests in AI, creativity and design.

Thank you for the invitation.
Sincerely,
Lilla LoCurto

**Comment by coreysmart92** [comment] 2015-08-25 20:17
Closing:
I have already responded. She sent me a message on August 20, and another on August 23. I responded on August 25. I am closing this because it is a duplicate of #124.

**Closed as completed by coreysmart92** 2015-08-25 20:17 UTC
