### ISSUE TITLE
New Podcast Cheat Sheet

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#64] opened 2015-05-18 18:44 UTC
Update and reorganize the [Podcast Production Cheat Sheet](https://docs.google.com/document/d/1G2KOpmqrrWR-hw4OLO9xn7UNhOM_QHf8kOuCuQ0342o/edit). For new and improved recording methods, which use Audacity as main recording software instead of Pamela.

**Comment by porteriffic** [comment] 2015-05-24 02:48
This is a duplicate of [this](https://github.com/creativedisturbance/podcasts/issues/10). 

Make sure we are updating cheat sheet for both Producers AND Voices.

**Comment by coreysmart92** [comment] 2015-05-25 18:59
The Cheat Sheets are updated. Need to be reviewed and moved to Creative Disturbance drive.

**Comment by porteriffic** [comment] 2015-05-28 00:49
@coreysmart92  Do you have an ETA on when they'll be able to be sent out to Producers and Voices? I'm getting a lot of podcast requests and I'm having to give them the outdated cheat sheets.

**Comment by coreysmart92** [comment] 2015-05-28 01:08
[The Producer Podcast Cheat Sheet](https://docs.google.com/document/d/1Io4Cj1Btt56jifbt4I8R1K4fdX1JYHPEzaYHbLAQBKY/edit) is completed, although I would still like feedback for improvements.  [The Guest Podcast Cheat Sheet](https://docs.google.com/document/d/1vlE3APrrN7_rRylUSuKdS8dvwDrDWd9PHG9QxpXZyJ4/edit) can be sent out if necessary, but the update was made to an old version. Remember that both of these documents reference the [H6 Zoom Recorder Guide](https://drive.google.com/open?id=0B0RS2YDJUln1S0ZsM0Jab2dVUVk&authuser=0) . The newest Guest Podcast Cheat Sheet will update by 7/1/15 at the latest. Will close this issue when the latest version of Guest Podcast Cheat Sheet is up.

**Comment by porteriffic** [comment] 2015-05-28 01:15
@coreysmart92 The screenshot needs to be placed near the steps you're guiding them through. Using bold or colored numbers will help when labeling the steps.

**Comment by coreysmart92** [comment] 2015-06-01 19:36
Close when content is completed, then open a new issue for visual design.

**Comment by coreysmart92** [comment] 2015-06-03 12:04
I have updated the content of the most recent [Guest/Voice Cheat Sheet](https://docs.google.com/document/d/1xpzeYtgntUoadfs68wZp-Nqs73oIgqz1rN0rGlErzIM/edit) .

I now need to work on the visual aspects of the Cheat Sheets. Close when completed.

**Comment by porteriffic** [comment] 2015-06-09 19:19
@coreysmart92 I highly recommend you get feedback from @heiwanalady, @cassininazir and @linamoon on creating graphics. Maybe they can assist in creating them.

**Closed as completed** 2015-06-29 18:19 UTC
Labels: On Hold
