### ISSUE TITLE
ken snelson podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#356] opened 2015-10-14 01:03 UTC
corey
please assign someone to work with paul to edit the ken snelson podcast
roger
Paul
The ken snelson podcast is at 
https://www.dropbox.com/s/kr6lvblcvm63l11/rec_k_snelson_05_Oct_2015_19_13_53.wmv?dl=0 

corey can you assign it to someone for editing and work with paul
to do this-there is a segment in the middle that needs to be edited out
-also its long- the final podcast will be about 40 minutes
Paul can tell you what periods to edit out

roger

**Comment by coreysmart92** [comment] 2015-10-15 18:55
Closing: Duplicate of issue #345 (10/15/15)

**Closed as completed by coreysmart92** 2015-10-15 18:55 UTC

**Comment by rmalina** [comment] 2015-10-27 22:34
corey
paul snelson would like to edit the snelsn podcast file but he needs in 
in a format he can edit such as .wav

can you send it to him as soon as possible
in the tracking sheet it says there is a file called
rec_k_snelson_05_Oct_2015_19_13_53.wav
can you send this to paul snelson

pls091020@utdallas.edu

roger

roger
@coreysmart92
