### ISSUE TITLE
orcid number

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#509] opened 2016-03-07 19:51 UTC
modify forms to allow voices and producers to add their ORCID numbers 
modify instructions so we encourage people to deposit their orcid number

cassini- not sure wha thte best approach is on this so assigning to you for now

roger

**Comment by cassininazir** [comment] 2016-05-03 02:46
Duplicate of #538. Closing this item.

**Closed as completed by cassininazir** 2016-05-03 02:46 UTC
