### ISSUE TITLE
determine criteria for what makes an acceptable podcast

### ISSUE THREAD

**Issue by dylanorgeron** [creativedisturbance/podcasts#531] opened 2016-03-21 19:35 UTC

**Comment by cassininazir** [comment] 2016-03-21 20:21
There may be a duplicate of this issue somewhere.

**Comment by amb141330** [comment] 2016-03-25 15:34
#431 is the issue number in regards to quality metrics. Closing this issue since it is a duplicate.

**Closed as completed by amb141330** 2016-03-25 15:34 UTC
Labels: Skedge
