### ISSUE TITLE
Transposh section in WordPress podcasts page

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#644] opened 2016-11-09 20:02 UTC
Ritwik and myself were curious if this section of the page was causing pages on Wordpress to load more slowly and if it's a necessary feature.

It seems that the loading of that feature is what requires the most time. It's on the top right of the page right above where you select the publication time.

**Comment by dylanorgeron** [comment] 2016-12-14 15:55
unlikely to be the cause, closing

**Closed as completed by dylanorgeron** 2016-12-14 15:55 UTC
Labels: Website
