### ISSUE TITLE
set up podcast with the harrisons for art and climate change

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#306] opened 2015-09-15 22:25 UTC
corey
when would you be available next monday to set up/record
podcast ?

roger

---------- Forwarded message ----------
From: Harrison Studio harrisonstudio@gmail.com
Date: Tue, Sep 15, 2015 at 5:05 PM
Subject: Re: The book
To: roger malina rmalina@alum.mit.edu
Cc: Janeil Engelstad janeil@mac.com, Corey Smart corey.smart92@gmail.com

Hi

I am available on the 21st after 2PM.

Newton

The Harrison Studio
335 Linden St.
Santa Cruz, CA 95062
www.theharrisonstudio.net
www.centerforforcemajeure.org
harrisonstudio@gmail

Helen Mayer Harrison/Newton Harrison
Co-Directors- Center for the Study of the Force Majeure
Professors Emeritus, UCSD
Research Professors- UC Santa Cruz
Principals- Harrison Studio

On Tue, Sep 15, 2015 at 1:35 PM, roger malina rmalina@alum.mit.edu wrote:
september ?
corey are you available on the 21st ?

roger

On Tue, Sep 15, 2015 at 2:36 PM, Janeil Engelstad janeil@mac.com wrote:
Roger, 

I will be with Newton and Helen in Santa Cruz the morning of Monday the 21st, perhaps we can schedule it for then?

Janeil

On Sep 15, 2015, at 2:34 PM, roger malina rmalina@alum.mit.edu wrote:

newton 

i have a new thing to suggest to you- on our creative disturbance platform
www.creativedisturbance.org we are going to do some podcasts around
art and climate change to coincide with COP21 at the end of november

would you be willing to do a skype with me and we can record a discussion ?
i am copying our senior sound designer corey smart who can help us schedule
and record it

we would need to do it by november 15

hoping you might be willing

janeil maybe you might want to do one with us too at the same time ?

roger

335 Linden St.
Santa Cruz, CA 95062
www.theharrisonstudio.net
www.centerforforcemajeure.org
harrisonstudio@gmail

Helen Mayer Harrison/Newton Harrison
Co-Directors- Center for the Study of the Force Majeure
Professors Emeritus, UCSD
Research Professors- UC Santa Cruz
Principals- Harrison Studio

O

Janeil Engelstad
Founding Director
MAP-Make Art with Purpose
www.makeartwithpurpose.net
www.janeilengelstad.net
www.voicesfromthecenter.net
phone 323-309-4837

**Comment by porteriffic** [comment] 2015-10-16 15:55
Closing. Podcast has been recorded.

**Comment by rmalina** [comment] 2015-10-17 02:38
please do not close until its published
roger

On Fri, Oct 16, 2015 at 10:55 AM, porteriffic notifications@github.com
wrote:

> Closing. Podcast has been recorded.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/306#issuecomment-148753511
> .

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by coreysmart92** [comment] 2015-11-02 17:27
Closing: This is a duplicate of issue #325. (11/2/15)

**Closed as completed by coreysmart92** 2015-11-02 17:27 UTC
Labels: Podcast, Art and Climate Change
