### ISSUE TITLE
Guests/Voices Cheat Sheet

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#10] opened 2015-02-19 19:32 UTC
Update cheat sheet with current recording software... if we are using Pamela still or not.

**Comment by porteriffic** [comment] 2015-03-05 23:23
I will work with Stephanie to make the cheat sheets look nicer, Corey will update with the new recording process.

**Comment by porteriffic** [comment] 2015-05-24 02:44
@coreysmart92 Do you have an update for us? I'm coordinating with Voices and Producers for Polyglot Day and unfortunately I have to send them our current cheat sheets which are highly out of date. 

I'm more than happy to work with you on this. Just name a time and/or date. Would like to get updated cheat sheet soon.

**Comment by coreysmart92** [comment] 2015-06-03 11:45
Closing because it is a duplicate of #64.

**Closed as completed by coreysmart92** 2015-06-03 11:45 UTC
