### ISSUE TITLE
 podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#397] opened 2015-11-21 19:04 UTC
corey\
you have got to do a better job dealing with emails
its embarassaing when i get emails like this

can you send her instructions on how to submit a podcast

thanks

roger

Lilla 

good to hear from you again- we are still welcoming podcasts

corey can you send lilla instructions on how to submit a podcast

roger

On Sat, Nov 21, 2015 at 12:55 PM, Lilla LoCurto loc.out@verizon.net wrote:

> Hi Roger,
> 
> It’s been awhile since your invitation for us to do a Podcast. We were in
> Germany working with Max Planck institute (an artist in residence) and when
> we returned to NY, a lot of personal stuff happened to us, making it
> difficult to address the Podcast. We wrote Corey twice and haven’t heard
> back so we thought we’d shoot an email your way. Anyway, we’re just now
> getting ready to do it and we’re wondering if it’s too late to submit
> something? Hopefully, not. Many thanks. Lilla
> ---
> 
> Lilla LoCurto/Bill Outcault
> http://locurto-outcault.com  
> 718.855.5348

**Comment by porteriffic** [comment] 2015-11-23 21:14
@rmalina Is this podcast for something specific? Either way we can accept their podcast. I can email them if you'd like.

**Comment by porteriffic** [comment] 2015-11-23 22:41
Emailed Lilla

**Comment by coreysmart92** [comment] 2015-11-30 17:44
Apologies I will be more careful in the future. I emailed her on 11/25/15, it seems everything is ready to go for the recording. Lilla said she would email if there are any complications.
Close: When the podcast has been submitted.

**Comment by coreysmart92** [comment] 2016-01-25 17:13
The podcast is scheduled and ready to publish.
Closing: Duplicate of another issue.
(1/25/16)

**Closed as completed by coreysmart92** 2016-01-25 17:13 UTC
Labels: Podcast
