### ISSUE TITLE
publish  ecoist and fqr podcasts week of 27 march

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#501] opened 2016-03-01 00:42 UTC
corey

can you schedule for publication these two podcasts for the week after march 27
with Alex Topete

yvan: can you record these two podcasts with me and alex after class monday march 7
with alex

one on his future ecoist review
one on
Feminist United Quaterly

roger
@yvantina

**Comment by coreysmart92** [comment] 2016-03-28 14:21
Closing: Duplicate of #515.

**Closed as completed by coreysmart92** 2016-03-28 14:21 UTC
