### ISSUE TITLE
Issue loading Creative Disturbance in other countries

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#655] opened 2017-02-19 20:43 UTC
I received an email that some of Annick Bureaud's colleagues couldn't access Creative Disturbance. I will paste the relevant email sections below.

"Roger, Ashton,

Erich is in Australia, so I asked an Australian friend to test the access. She is reporting the same problem as Erich, that it times out. She also says that it is not allowed to take a screen shot of the website  ?!

So, in Europe we can access it without problem but not in Australia ?! I guess there is some kind of problem in relation to the geography but I have no clue which one ...
Would be interesting to know if it is only Australia or also Asia and South America ...
Could someone try to figure that out ?

Thanks
Annick"

"Her exact message is :

the index page loads, but clicking on the individual podcasts says, web page not available.
Taking screenshots is not permitted on your site but the error message was " timed out""

**Does anyone know how to resolve this?**

**Comment by cassininazir** [comment] 2017-02-20 16:31
@duncangallagher could you investigate as well? 

Try using a plugin like Hola Unblocker  to spoof the browser into thinking you are visiting from specific parts of the world.

**Comment by magicspacekiwi** [comment] 2017-02-20 19:21
I'll be in today and will check this out.

AFAIK this may just be an issue with the HostGator server being very slow.

The inability to screenshots may happen if she's using a browser extension to take screenshots (often they don't work on built-in error pages which a connection timeout may generate).

**Comment by magicspacekiwi** [comment] 2017-02-20 20:41
I tested the site via VPN service and accessed the site through servers in Sydney and Melbourne using Chrome v55 on macOS 10.12.1

@cassininazir The results were the same both times; the site was extremely slow to respond, but I was able to stream podcasts. Closing as I am unable to reproduce the issue.

**Closed as completed by magicspacekiwi** 2017-02-20 20:41 UTC
Labels: Website

**Comment by magicspacekiwi** [comment] 2017-02-21 00:35
@amb141330 I've closed this issue because I don't think there's anything we can do about this for now.

The problem may go away when we migrate to better servers, but it'd be nice to have more details to see if we can reproduce it and ensure that the new server doesn't suffer from those issues.

Can you see if they can provide:

- Operating System Version _(e.g. Windows 10, macOS 10.12)_

- Browser Version _(e.g. Chrome 55)_

- Approximate Connection Speed or Type _(e.g. 50 Mbps, Cable)_

- Location _(city)_

- The screenshot utility they are using

**Comment by magicspacekiwi** [comment] 2017-02-21 00:50
@amb141330 Also, I tested access from some other locations like you suggested and found no problems other than poor performance (as expected) from any of the following places:

- Seoul, South Korea
- Tokyo, Japan
- Hong Kong, China
- Singapore
- São Paulo, Brazil

**Comment by magicspacekiwi** [comment] 2017-02-21 01:18
FYI @amb141330 

I've opened https://github.com/artscilab/admin/issues/72 to discuss options for better hosting.

**Comment by cassininazir** [comment] 2017-02-21 02:37
Thanks @colin-c for this thorough review.
