### ISSUE TITLE
An SFU channel ?

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#226] opened 2015-08-23 01:49 UTC
@cassininazir @porteriffic @linamoon @coreysmart92 
more to come

hi roger and yvan,

this is a wonderful idea!

It just so happens that I will be the new director of SIAT starting 1 Sept 2015.
I will follow up with you when I return from my vacation after 1 september 2015 

thecla

---

d r   t h e c l a   s c h i p h o r s t
symposium director ISEA2015
associate director SIAT | professor
director movingStories research partnership
school of interactive arts + technology
simon fraser university
m 604.726.9364
e thecla@sfu.ca
www.sfu.ca/~tschipho
www.movingstories.ca 
www.isea2015.org 

---

From: "roger malina" rmalina@alum.mit.edu
To: "Yvan Tina" yvantina@gmail.com
Cc: "Philippe Pasquier" philippe_pasquier@sfu.ca, isea2015-thecla@sfu.ca, hdaniel@sfu.ca
Sent: Thursday, August 20, 2015 8:27:35 PM
Subject: Re: SFU School of Interactive Art on Creative Disturbance ?

Philippe, Thecla and Daniel
first apologies for my no show at ISEA=by all reports it was a great isea
but delighted that Yvan connected with you
in any case as yvan indicated creative disturbance is available to you
( we are also starting an aggregation service where we re post podcasts
you have already published- as a different option to setting up a channel)
we are moving the platform to mit press with a mit url which will also
help draw audience

roger

On Thu, Aug 20, 2015 at 10:02 PM, Yvan Tina yvantina@gmail.com wrote:

> Dear Philippe, Thecla and Daniel
> -cc Roger Malina
> 
> it was very nice chatting with you at Isea and thanks again for the great
> work you've done to make it a successful event !!
> 
> Just wanted to bring your attention to Creative Disturbance, the Leonardo
> audio platform for discussions on art, science and technology
> (http://creativedisturbance.org/ 
> ) and suggest the idea, as we already
> pointed out, of having a channel produced by the School of Interactive Art
> faculty (and/or students); but if you rather like that option, you can
> simply send us your podcasts on art/sci/tech and we'll be happy to release
> it online (oui, après édition cher Philippe...)
> However, having a channel (a disturbance) give you more freedom on the
> content as producers since the podcast usually reflects the overall theme of
> your channel and it only requires a minimum of 7-8 podcasts a year to be
> kept active.. The logo can be designed either by you or our design team.. In
> any case, we can perfectly manage with your preference and work with the
> most convenient solution !
> The average length of a podcast is 15mn and it can be in any spoken language
> (i.e French of course, but Chinese, German, Swahili..).
> Feel free to send us more recommendations about things you'd like to hear,
> ideas you want to discuss and people of interest we need to contact for a
> podcast..
> We have more channels on their way and we're nearing about 15000 downloads
> after one year of activity. so please check it out !
> 
> Kind regards
> 
> yvan

**Comment by porteriffic** [comment] 2015-10-16 14:50
@yvantina Is there an update on this?

**Comment by yvantina** [comment] 2015-10-16 23:46
@porteriffic @coreysmart92  No, but we received a proposal for a new channel from Diane Gromala and her Phd Student from SFU - see with Corey . Not sure if this will be the SFU channel I was talking about (see above) but it is anyway already a good news !

**Comment by porteriffic** [comment] 2015-10-19 16:01
@yvantina Great! I'll have Corey provide an update for us and we can start another GitHub item and close this one.

**Comment by porteriffic** [comment] 2015-10-23 15:19
@coreysmart92 Please email me an update.

**Comment by porteriffic** [comment] 2015-12-11 16:24
@coreysmart92 Need an update on this ASAP.

**Comment by yvantina** [comment] 2015-12-11 19:32
Corey, I think it took too much time now quickly. It was 3 months ago and
we did not react enough quickly. I hope they're still willing to open a
'Nowhere Else' channel but I'm afraid they already busy with other
projects.. let see. Keep us posted

**Comment by porteriffic** [comment] 2015-12-14 17:43
This issue is a duplicate of #357.

**Closed as completed by porteriffic** 2015-12-14 17:43 UTC
Labels: On Hold, New Channel
