### ISSUE TITLE
guy edmonds for audiovisual archive day

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#307] opened 2015-09-15 22:31 UTC
corey
can you set up and schedule this podcast recording

roger

Guy Edmonds via alum.mit.edu 
4:01 PM (1 hour ago)

to roger, Guy, Corey 
Yes, no problem to set it up during my evening.

Guy

On 15/09/2015 21:32, "roger malina" rmalina@alum.mit.edu wrote:

> guy
> great
> corey can i let you set this up with guy and
> me ! and record it
> 
> with the time zone differerence its a bit tricky
> guy could you do it from home ?
> 
> roger
> 
> On Tue, Sep 15, 2015 at 3:02 PM, Guy Edmonds guy.edmonds@plymouth.ac.uk
> wrote:
> 
> > Hi Roger,
> > 
> > Yes, that would be fine with me. We're not actually going on Honeymoon
> > just yet but I will be going back to visit my ailing Mum after the
> > wedding
> > so if we could set something up from week beginning 28 Sept that should
> > work for me.
> > 
> > Many thanks for your input last week and good to catch up
> > 
> > Best
> > 
> > Guy
> > 
> > Guy Edmonds
> > 
> > Marie Curie Fellow of Early Cinema and Cognitive Creativity
> > 
> > Contributing Researcher: Transtechnology Research
> > 
> > CogNovo | Link 3 | University of Plymouth | Drake Circus | Plymouth |
> > Devon | PL4 8AA
> > 
> > www.cognovo.eu
> > 
> > trans-techresearch.net
> > 
> > On 15/09/2015 20:28, "roger malina" rmalina@alum.mit.edu wrote:
> > 
> > > guy
> > > 
> > > sorry i was too tired to do a podcast recording with you
> > > before i left
> > > 
> > > i know you are getting married next week ! yeah !
> > > 
> > > would you be willing to record a podcast over skype
> > > when you get back from your honeymoon
> > > 
> > > we would like to do it by october 20th so we can edit it
> > > and have it on line for our audio visual heritate day oct 27
> > > 
> > > i am copying corey smart our senior sound design who
> > > can help us set up and record the skype
> > > ## 
> > > 
> > > Roger F Malina
> > > is in Dallas
> > > 1-510-853-2007

**Comment by porteriffic** [comment] 2015-10-23 15:47
Duplicate of #339. Closing

**Closed as completed by porteriffic** 2015-10-23 15:47 UTC
