### ISSUE TITLE
Noisy People Podcast Titles

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#82] opened 2015-05-27 07:48 UTC
this podcast title is inadequate =only has the name of the guest

http://creativedisturbance.org/podcast/03-ignaz-schick/

please the sound editor is responsible for making sure the podcast title
is good and follows our title guidleines

roger

**Comment by porteriffic** [comment] 2015-05-28 00:46
@rmalina This is a Noisy People podcast and all podcasts from Tim Perkis are titled this way. He uses this format on iTunes and his website as well. I can ask him to revise his titles for us, but I doubt he'll comply.

**Comment by coreysmart92** [comment] 2015-06-03 07:40
Closing because as Josephine has mentioned this is the style that Tim Perkis prefers and all of these come completed and ready to publish, @porteriffic you know the most about Noisy People so if anything changes make a new issue and let us know.

**Comment by rmalina** [comment] 2015-06-03 18:25
i disagree with this decision- tim perkis will happily change his podcast titles if you
work it with him so its not just the name of the person
have you contacted tim ? copy me on your email to him and i will insist

roger

**Comment by porteriffic** [comment] 2015-06-03 22:26
@rmalina I will email him this week and ask if he will change the titles of his podcasts. I'll CC you in the email.

**Comment by rmalina** [comment] 2015-06-04 00:17
i emailed him and he said he was more than happy- he hadnt received any instructions on how we like the titles written-do we need to send all producers a request to improve their titles and give them guidleines

**Comment by porteriffic** [comment] 2015-06-04 01:24
@rmalina Great!

A title guideline has been on the back burner for a while. I will email Tim this week but would like to delegate creating the guideline to another team member. 

@halclark @coreysmart92 @halclark @kkondas Would one of you please assist in creating a guideline for creative and unique podcast titles?

**Comment by porteriffic** [comment] 2015-06-04 01:56
Emailed Tim.

**Comment by porteriffic** [comment] 2015-06-09 18:03
Closing this since it is now a duplicate of Issue #97

**Closed as completed by porteriffic** 2015-06-09 18:03 UTC
