### ISSUE TITLE
orcid numbers

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#538] opened 2016-03-25 16:29 UTC
please add to the voice form an entry for voices to provide their orcid number
http://orcid.org/

roger

@ChazLilly 
chaz can you put the need for orcid numbers of authors into the grey lit plan

**Comment by rmalina** [comment] 2016-03-25 16:29
http://orcid.org/ 

is the reference

**Comment by cassininazir** [comment] 2016-05-03 02:46
Duplicate of #543. Closing this item.

**Closed as completed by cassininazir** 2016-05-03 02:46 UTC
