### ISSUE TITLE
improve work on the podcast cheat sheet for people submitting podcasts

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#123] opened 2015-07-15 18:14 UTC
_From @rmalina on July 12, 2015 14:0_

we really need to improve the cheat sheet for people submitting podcasts -either new producers or people invited to submit a podcast-i worked on it a bit but right now it is really user unfriendly and i suspect incomprehensible to people trying to submit a podcast

https://docs.google.com/document/d/1Io4Cj1Btt56jifbt4I8R1K4fdX1JYHPEzaYHbLAQBKY/edit

the section on how to submit a podcast is problematic right now= are the dropbox folders
open to the world ? we really need to tell people submitting podcasts to submit spefically to the voices of the crowd channel and given them the exact link-right now its really confusing

cassini-not sure who the right person to work on this is but we really need a user friendly versoin

there is no document number

i added a date

roger

_Copied from original issue: creativedisturbance/intellectual-dating#21_

**Comment by porteriffic** [comment] 2015-10-23 17:48
Duplicate of #141. Closing

**Closed as completed by porteriffic** 2015-10-23 17:48 UTC
