### ISSUE TITLE
Create Community Building Plan

### ISSUE THREAD

**Issue by halclark** [creativedisturbance/podcasts#194] opened 2015-07-20 07:06 UTC
_From @cassininazir on March 2, 2015 22:9_

_From @cassininazir on January 22, 2015 18:31_

This should identify ways to foster a community among the disturbers. Not all preliminary research needs to be complete as this can be a living document. 

_Copied from original issue: cassininazir/creativedisturbance#44_

_Copied from original issue: creativedisturbance/public-website#38_

**Comment by halclark** [comment] 2015-07-20 07:06
_From @heiwanalady on July 16, 2015 19:56_

Our current plan document
https://docs.google.com/document/d/1qOUdULI8sq3-Lls5S6obyZDaVqEG_tt4aHdpKh75S5w/edit

**Comment by halclark** [comment] 2015-07-20 07:06
_From @rmalina on July 16, 2015 20:10_

now to actually implement it
can i suggest you create a section where its clear who on our team is individually responsible for implementing which part of this plan ! its a great plan but we certainly arent doing it yet
roger

**Comment by porteriffic** [comment] 2015-07-31 22:17
This is a duplicate of [this](https://github.com/creativedisturbance/podcasts/issues/160)

**Closed as completed by porteriffic** 2015-07-31 22:17 UTC
